# --- !Ups

CREATE TABLE PACIENTES (
  id         INTEGER AUTO_INCREMENT PRIMARY KEY,
  nombre     VARCHAR,
  apellido   VARCHAR,
  dni        INTEGER,
  obrasocial INT
);

CREATE TABLE MEDICOS (
  id        INTEGER AUTO_INCREMENT PRIMARY KEY,
  matricula INTEGER,
  nombre    VARCHAR,
  apellido  VARCHAR,
  usuario   VARCHAR,
  password  VARCHAR
);

CREATE TABLE RECEPCIONES (
  id          INTEGER AUTO_INCREMENT PRIMARY KEY,
  idMedico    INTEGER,
  idPaciente  INTEGER,
  diagnostico VARCHAR,
  prioridad   VARCHAR,
  fecha       DATETIME,
  FOREIGN KEY (idMedico) REFERENCES MEDICOS (id),
  FOREIGN KEY (idPaciente) REFERENCES PACIENTES (id)
);

CREATE TABLE ADMINISTRADORES (
  id        INTEGER AUTO_INCREMENT PRIMARY KEY,
  nombre    VARCHAR,
  apellido  VARCHAR,
  usuario   VARCHAR,
  password  VARCHAR
);
# --- !Downs

DROP TABLE IF EXISTS PACIENTES;
DROP TABLE IF EXISTS MEDICOS;
DROP TABLE IF EXISTS ADMINISTRADORES;
DROP TABLE IF EXISTS RECEPCIONES;
